### ISSUE TITLE
error: OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by manvirvirk** [juntang-zhuang/LadderNet#11]
path_data = config.get('data paths', 'path_local')
  File "C:\Users\virkt\Anaconda3\envs\code\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\Users\virkt\Anaconda3\envs\code\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'data paths'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument
  can anyone help out?

**Comment by yrgenkuci** [comment]
Depends, what are you trying to do here?

**Comment by manvirvirk** [comment]
@AnthonyKuci  i m getting broken pipe error while running training file. Can you please file?Thanks
traceback is:
  0%|                                                                                                                                                                                      | 0/17 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\virkt\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\virkt\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\virkt\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\LadderNet-master\src\retinaNN_training.py", line 206, in <module>
    train(epoch)
  File "D:\LadderNet-master\src\retinaNN_training.py", line 164, in train
    for batch_idx, (inputs, targets) in enumerate(tqdm(train_loader)):
  File "C:\Users\virkt\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "C:\Users\virkt\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\virkt\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)Traceback (most recent call last):

  File "retinaNN_training.py", line 206, in <module>
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    train(epoch)
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
  File "retinaNN_training.py", line 164, in train
    return Popen(process_obj)
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    for batch_idx, (inputs, targets) in enumerate(tqdm(train_loader)):
    prep_data = spawn.get_preparation_data(process_obj._name)  File "C:\Users\virkt\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 1005, in __iter__

      File "C:\Users\virkt\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
for obj in iterable:
  File "C:\Users\virkt\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    _check_not_importing_main()
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\virkt\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
        is not going to be frozen to produce an executable.''')
RuntimeError: w.start()

        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\process.py", line 112, in start

    self._popen = self._Popen(self)
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\virkt\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
