### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by LJM-GitHub** [juntang-zhuang/LadderNet#2]
root@ip:/home/ubuntu/workspace/LadderNet/src# python retinaNN_training.py 
Traceback (most recent call last):
  File "retinaNN_training.py", line 17, in <module>
    from lib.help_functions import *
  File "../lib/help_functions.py", line 4, in <module>
    from matplotlib import pyplot as plt
  File "/root/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/anaconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/root/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/root/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/root/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/root/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/root/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 140, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by juntang-zhuang** [comment]
It seems like a problem with your matplotlib

**Comment by LJM-GitHub** [comment]
thanks，
My solution：
pyqt：5.6.0 --> pyqt：5.9.2
the  executive command:
`conda install pyqt=5.9.2`

**Comment by y-aiydec** [comment]
% docker logs 00d4a9b8c42e
Traceback (most recent call last):
  File "./app/ziniav01.py", line 6, in <module>
    from PyQt5 import QtCore, QtWidgets, QtGui
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
